### ISSUE TITLE
And it so it begins

### ISSUE THREAD

**Issue by JDillon522** [notblackburn/training#1]
Welcome to your first official github issue. You'll have many more and they tend to proportionally correspond to the level of your despair. 

Your first mission will be to review and merge the pull request that will mention this issue.

Your second mission will be to grant me collaborator rights. A simple search should show you to the github help page that'll walk you through it if you arent already familiar. 

Last mission, close this issue and rejoice.

Or cry because your soul is now mine.

Six to one, half a dozen to another.

**Comment by notblackburn** [comment]
Ok. First question.  I merged your commit and mentioned "fix issue #1" in the comments.  According to the class, just mentioning fixed issue #1 should have closed the issue, but it did not. Please explain.  I purposely haven't closed it until I talk to you.
